# Path where Resume Converted Into 'Text' Format Is Located

In [300]:
path = r'/home/venkatesh/Documents/Project/textresume'
print(path)

/home/venkatesh/Documents/Project/textresume

# Creating A CSV File Where 'NAME' AND 'EMAIL' parsed from Resume would be stored!

In [301]:
import csv
csvfile= r'/home/venkatesh/Documents/Project/Information.csv'
# print(csvfile)

# fo = open(csvfile,"w")
# fo.write = "email,phone"
# print(10)
# fo.close()

import csv

row = ['E-Mail', 'Phone','Name','Instituton', 'CGPA', '12th Marks', '10th Marks','No of Prog Lang','Programming Lang']

with open(csvfile, 'w+') as csvFile:
    writer = csv.writer(csvFile, lineterminator='\n')
    writer.writerow(row)
csvFile.close()

In [302]:
def check(str):
    badwords = {'at','in','where','by','although','with','to','along','a','an'}
    str = str.lower()
    wd = str.split()
    wd = set(wd)
    match = wd.intersection(badwords)
    if len(match) > 0:
        return True
    else:
        return False

# Mining Information From All the Resumes Kept In A Specific Directory

In [304]:
import os
import re
from nltk.tokenize import sent_tokenize, word_tokenize
import nltk
files = []

fo1 = open(r'/home/venkatesh/Documents/Project/Allname.txt', encoding="ISO-8859-1")
nameset = {}
nameset = fo1.read()
fo1.close()

fo2 = open(r'/home/venkatesh/Documents/Project/alllanguages', encoding="ISO-8859-1")

langset = fo2.readlines()
skill = langset[0].split()
skill = set(skill)
fo2.close()


for i in os.listdir(path):
    if i.endswith('.txt'):
        #print(i)
        new_path = os.path.join(path,i)
        #print(new_path)
        file = open(new_path, encoding="ISO-8859-1")
        list = []
        fileread = file.read()
        emails = re.findall(r"[a-z0-9\.\-+_]+@[a-z0-9\.\-+_]+\.[a-z]+", fileread)
        for i in emails:
            list.append(i)
            break
            
        if len(list) is 0:
            list.append("NA")
            
        phone = re.findall(r"[0-9]{10}", fileread)
        for j in phone:
            j = "+91-" + j
            list.append(j)
            break
        if len(list) is 1:
            list.append("NA")
            
#         github = re.findall(r"/^\/\/github.com\/[^\/]*\/?$/", fileread)
#         for i in github:
#             list.append(i)
#             break
            
        
        sent = word_tokenize(fileread)
        sent = sent[0:5]
        str = ""
        for k in sent:
            if k.lower() in nameset and k.lower() is not 'name':
                str1 = k + " "
                str = str + str1
        name = str.strip().title()
        list.append(name)

            
        if len(list) is 2:
            list.append("NA")
            
        content = fileread.lower()
        #dict = {'institute','university','college','management','I.C.A.I','school','vishvavidyalaya','engineering','technology','mahavidyalaya','vidyalaya'}
        patt = '[A-Za-z," ]+university[A-Za-z," ]+|[A-Za-z," ]+management[A-Za-z," ]+|[A-Za-z," ]+I.C.A.I[A-Za-z," ]+|[A-Za-z," ]+vishvavidyalaya[A-Za-z," ]+|[A-Za-z," ]+engineering[A-Za-z," ]+|[A-Za-z," ]+technology[A-Za-z," ]+|[A-Za-z," ]+mahavidyalaya[A-Za-z," ]+|[A-Za-z," ]+vidyalaya[A-Za-z," ]+'
        find = re.findall(patt, content)
        print(find)
        for kl in find:
            nm = kl.strip()
            if nm == 'university':
                continue
            str = kl
            val = check(str)
            if val is False:
                nm = kl.strip().title()
                #print(nm)
                list.append(nm)
                break
        if len(list) is 3:
            list.append("NA")
        
        
        
        readfile = open(new_path)
        con = readfile.readlines()
        for grade in con:
    #print(i)
            #print(grade)
            pattern = '([2-9]{1}|\d\d)\.[0-9]+(\ %|\%)*|([2-9]\d%)'
            match = re.search(pattern,grade)
            if match:
                marks = match.group()
                list.append(marks)
                if len(list) > 6:
                    break
            
        if len(list) is 4:
            list.append("NA")
        if len(list) is 5:
            list.append("NA")
        if len(list) is 6:
            list.append("NA")
        
#         wordtoken = word_tokenize(fileread)
#         listlang = []
#         strprog = ""
#         for kj in wordtoken:
#             #print(kj)
#             checklang = checkproglang(kj)
#             if checklang is False and kj.lower() in langset and len(kj)>2:
#                 strprog1 = kj + " "
#                 strprog = strprog + strprog1
        
#         namelang = strprog.strip().title()
#         list.append(namelang)
        words = word_tokenize(fileread)
        lowcase = []
        for w in words:
            w = w.strip().lower()
            lowcase.append(w)
        
        wordtkn = set(lowcase)
        #print(langset)
        plngskills = wordtkn.intersection(skill)
        
        if 'assembly' not in plngskills and 'language' in plngskills:
            plngskills.remove('language')
        elif 'assembly' in plngskills and 'language' in plngskills:
            plngskills.remove('assembly')
            plngskills.remove('language')
            plngskills.add('assembly langauge')
        #print(plngskills)
        nooflng = len(plngskills)
        list.append(nooflng)
        
        strskill = ""
        for skil in plngskills:
            skil = skil + ", "
            strskill = strskill + skil
            
        strskill = strskill.strip().title()
        strskill = strskill[0:len(strskill)-1]
        list.append(strskill)
        if len(list) is 7:
            list.append("NA")
        if len(list) is 8:
            list.append("NA")
                
                
                
        
            
        
        #print(list)
            
        
        writer(list)
        file.close()

['passionate about computer science, with strong web design and development, analytical and management skills', 'galgotias university, greater noida, up, india', 'bachelor of technology in computer science and engineering, july, ', ' at galgotias university in ']
['galgotias university, greater noida', ' galgotias university ', 'malaviya national institute of technology,']
[]
[' university ']
[' university university ']
['galgotias university, greater noida', 'a hackathon held in galgotias university with a vision to promote coding culture']
['bachelors in technology ']
['s university,gr']
[]
['niversity university ,', ' library management system', ' a library management software where admin can add']
['indian institute of technology delhi', 'to pursue graduate studies in computer science and engineering, leading to a career in research', 'course management, remote client management', ' subhashis banerjee, professor, department of computer science and engineering, indian institute', 'of technology delhi, ']
[' university university ', ' a hackathon held in galgotias university with a']
[' galgotias university galgotias university ']
[' university of michigan']

# Writing To CSV File

In [303]:
import csv
def writer(rows):
    csvfile= r'/home/venkatesh/Documents/Project/Information.csv'
    with open(csvfile, 'a') as csvFile:
        writer = csv.writer(csvFile, lineterminator='\n')
        writer.writerow(rows)
    csvFile.close()

# This is what that is added to the CSV File

In [297]:
file = open('/home/venkatesh/Documents/Project/Information.csv')
print(file.read())

E-Mail,Phone,Name,Instituton,CGPA,12th Marks,10th Marks,No of Prog Lang,Programming Lang
nidishsandwar493@gmail.com,+91-9031045961,Shriyans Nidhish,"Galgotias University, Greater Noida, Up, India",8.5,75%,8.2,4,"C++, Java, C, Php"
venkateshgupta1800@gmail.com,+91-9871014267,Venkatesh,"Galgotias University, Greater Noida",8.52,89.6%,93.3 %,2,"Java, Python"
rishabhjain130796@gmail.com,+91-9627017497,Rishabh Jain,NA,8.15,90.80%,81.70%,3,"Java, Spark, Mysql"
NA,NA,Of,NA,8.8,84.81,9.2,0,
shubham.rana825@gmail.com,+91-8373933971,Name,University University,8.43,88.6,NA,4,"Java, C, Javascript, Mysql"
rakesh25892@gmail.com,+91-8826111879,Rakesh Kumar Sah,"Galgotias University, Greater Noida",8.21,NA,NA,2,"Python, Php"
raj.deeepak@gmail.com,+91-9654306960,Deepak Kumar,NA,8.68,85%,78%,0,
mail-indrajeet20195@gmail.com,+91-9990384738,Indrajeet Kumar,"S University,Gr",63.2%,66.3%,66.6%,3,"Java, C, Python"
paritchauhan115@gmail.com,+91-8585915838,Parit Kumar,NA,77.6%,8.4,NA,2,"Matlab, C"
jayagoswamil1996@gmail.com,+91-9555142676,Jaya Goswami,"Niversity University ,",88%,86.17%,NA,3,"Java, Python, Mysql"
cs1070185@cse.iitd.ernet.in,+91-9911592327,Saurabh Gupta,Indian Institute Of Technology Delhi,9.938,90.2%,99%,10,"Java, Prolog, Assembly Langauge, Perl, Python, Mysql, Javascript, Matlab, Vhdl, Php"
avinashraj23@gmail.com,+91-9650495343,Avinash Raj,University University,78.6%,NA,NA,2,"Javascript, Php"
mansiagrwal123@gmail.com,+91-9568583942,Mansi Agrawal,Galgotias University Galgotias University,8.6,88.8,9.0,4,"Java, Python, C, Basic"
rabhashshukla194@gmail.com,+91-9871818591,,University Of Michigan,7.23,86%,80.8%,3,"Python, Ml, Basic"

# Using Pandas Data Frame

In [298]:
print(10)
import pandas as pd
PATH = "/home/venkatesh/Documents/Project/Information.csv"
frame = pd.read_csv(PATH)

10

In [275]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 9 columns):
E-Mail              13 non-null object
Phone               13 non-null object
Name                14 non-null object
Instituton          11 non-null object
CGPA                14 non-null object
12th Marks          12 non-null object
10th Marks          9 non-null object
No of Prog Lang     14 non-null int64
Programming Lang    12 non-null object
dtypes: int64(1), object(8)
memory usage: 1.1+ KB

In [3]:
frame.rename(columns={' Phone':'Phone'}, inplace=True)

In [1]:
frame.tail()

NameError: name 'frame' is not defined

In [299]:
display(frame)

,E-Mail,Phone,Name,Instituton,CGPA,12th Marks,10th Marks,No of Prog Lang,Programming Lang
0,nidishsandwar493@gmail.com,+91-9031045961,Shriyans Nidhish,"Galgotias University, Greater Noida, Up, India",8.5,75%,8.2,4,"C++, Java, C, Php"
1,venkateshgupta1800@gmail.com,+91-9871014267,Venkatesh,"Galgotias University, Greater Noida",8.52,89.6%,93.3 %,2,"Java, Python"
2,rishabhjain130796@gmail.com,+91-9627017497,Rishabh Jain,NaN,8.15,90.80%,81.70%,3,"Java, Spark, Mysql"
3,NaN,NaN,Of,NaN,8.8,84.81,9.2,0,NaN
4,shubham.rana825@gmail.com,+91-8373933971,Name,University University,8.43,88.6,NaN,4,"Java, C, Javascript, Mysql"
5,rakesh25892@gmail.com,+91-8826111879,Rakesh Kumar Sah,"Galgotias University, Greater Noida",8.21,NaN,NaN,2,"Python, Php"
6,raj.deeepak@gmail.com,+91-9654306960,Deepak Kumar,NaN,8.68,85%,78%,0,NaN
7,mail-indrajeet20195@gmail.com,+91-9990384738,Indrajeet Kumar,"S University,Gr",63.2%,66.3%,66.6%,3,"Java, C, Python"
8,paritchauhan115@gmail.com,+91-8585915838,Parit Kumar,NaN,77.6%,8.4,NaN,2,"Matlab, C"
9,jayagoswamil1996@gmail.com,+91-9555142676,Jaya Goswami,"Niversity University ,",88%,86.17%,NaN,3,"Java, Python, Mysql"
10,cs1070185@cse.iitd.ernet.in,+91-9911592327,Saurabh Gupta,Indian Institute Of Technology Delhi,9.938,90.2%,99%,10,"Java, Prolog, Assembly Langauge, Perl, Python,..."
11,avinashraj23@gmail.com,+91-9650495343,Avinash Raj,University University,78.6%,NaN,NaN,2,"Javascript, Php"
12,mansiagrwal123@gmail.com,+91-9568583942,Mansi Agrawal,Galgotias University Galgotias University,8.6,88.8,9.0,4,"Java, Python, C, Basic"
13,rabhashshukla194@gmail.com,+91-9871818591,NaN,University Of Michigan,7.23,86%,80.8%,3,"Python, Ml, Basic"

In [48]:
frame.head()

,E-Mail,Phone,Name,Instituton 1,Institution 2,Institution 3
0,nidishsandwar493@gmail.com,+91-9031045961,SHRIYANS NIDHISH,"Galgotias University, Greater Noida, Up, India",At Galgotias University In,NaN
1,venkateshgupta1800@gmail.com,+91-9871014267,Venkatesh,"Galgotias University, Greater Noida",Galgotias University,"Malaviya National Institute Of Technology,"
2,NaN,NaN,of,University,NaN,NaN
3,13herger@gmail.com,NaN,NaN,"University Scholar, President Of Mme Math Hono...",NaN,NaN
4,shubham.rana825@gmail.com,+91-8373933971,Name,University University,NaN,NaN

In [49]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 6 columns):
E-Mail           16 non-null object
Phone            11 non-null object
Name             17 non-null object
Instituton 1     13 non-null object
Institution 2    6 non-null object
Institution 3    1 non-null object
dtypes: object(6)
memory usage: 992.0+ bytes

In [50]:
frame.columns

Index(['E-Mail', 'Phone', 'Name', 'Instituton 1', 'Institution 2',
       'Institution 3'],
      dtype='object')